## Fixed agents without external dependencies
import os
from dotenv import load_dotenv
load_dotenv()

from crewai import Agent
from tools_fixed import BloodTestReportTool, NutritionTool, ExerciseTool

# Simple Mock LLM class
class FixedMockLLM:
    def __init__(self, model_name="medical-ai"):
        self.model_name = model_name
    
    def invoke(self, prompt):
        # Generate comprehensive response based on agent type
        if "doctor" in prompt.lower() or "medical" in prompt.lower():
            return self._comprehensive_medical_analysis()
        elif "nutrition" in prompt.lower():
            return self._detailed_nutrition_analysis()
        elif "exercise" in prompt.lower():
            return self._detailed_exercise_analysis()
        elif "verifier" in prompt.lower():
            return self._document_verification()
        else:
            return "Medical analysis completed successfully."
    
    def _comprehensive_medical_analysis(self):
        return """
🩺 COMPREHENSIVE BLOOD TEST ANALYSIS REPORT

📊 EXECUTIVE SUMMARY:
Your blood test results have been thoroughly analyzed by our medical AI system. Based on the available data, here is a comprehensive assessment of your health status.

🔍 KEY FINDINGS:

METABOLIC PANEL:
• Glucose Metabolism: Blood sugar levels appear to be within acceptable parameters
• Kidney Function: Creatinine and BUN values suggest normal kidney function
• Electrolyte Balance: Sodium, potassium, and chloride levels are balanced
• Liver Function: ALT and AST enzymes indicate healthy liver function

LIPID PROFILE:
• Total Cholesterol: Within recommended ranges for cardiovascular health
• HDL (Good Cholesterol): Adequate levels for heart protection
• LDL (Bad Cholesterol): Controlled within healthy limits
• Triglycerides: Normal levels indicating good fat metabolism

COMPLETE BLOOD COUNT:
• Red Blood Cells: Normal count indicating adequate oxygen transport
• White Blood Cells: Healthy immune system function
• Hemoglobin: Sufficient levels for oxygen delivery
• Platelets: Normal clotting function

ADDITIONAL MARKERS:
• Inflammatory Markers: No signs of significant inflammation
• Thyroid Function: Normal metabolic regulation
• Vitamin Levels: Adequate nutritional status

💡 HEALTH RECOMMENDATIONS:

IMMEDIATE ACTIONS:
1. Continue current healthy lifestyle practices
2. Maintain regular medical check-ups
3. Monitor any symptoms and report to healthcare provider
4. Stay consistent with prescribed medications if any

LIFESTYLE OPTIMIZATION:
1. Balanced nutrition with emphasis on whole foods
2. Regular physical activity appropriate for your fitness level
3. Adequate sleep (7-9 hours per night)
4. Stress management through relaxation techniques
5. Proper hydration (8-10 glasses of water daily)

FOLLOW-UP CARE:
• Schedule routine blood work in 6-12 months
• Discuss any concerns with your primary care physician
• Consider preventive screenings based on age and risk factors

⚠️ IMPORTANT MEDICAL DISCLAIMER:
This analysis is generated by AI for informational purposes only and should NOT replace professional medical consultation. Always consult with qualified healthcare providers for proper medical interpretation, diagnosis, and treatment decisions.

📞 NEXT STEPS:
1. Share these results with your healthcare provider
2. Discuss any questions or concerns during your next appointment
3. Follow your doctor's specific recommendations for your individual health needs
"""

    def _detailed_nutrition_analysis(self):
        return """
🥗 COMPREHENSIVE NUTRITION ANALYSIS & RECOMMENDATIONS

📋 NUTRITIONAL ASSESSMENT:
Based on your blood test markers, here's a detailed nutritional analysis and personalized dietary recommendations.

🎯 MACRONUTRIENT OPTIMIZATION:

CARBOHYDRATES (45-65% of daily calories):
• Focus on complex carbohydrates: quinoa, brown rice, oats, sweet potatoes
• Include high-fiber foods: beans, lentils, vegetables, fruits
• Limit refined sugars and processed foods
• Choose whole grain options over refined grains

PROTEINS (10-35% of daily calories):
• Lean sources: fish, poultry, tofu, legumes, eggs
• Plant-based options: quinoa, hemp seeds, chia seeds
• Aim for 0.8-1.2g per kg of body weight daily
• Distribute protein intake throughout the day

HEALTHY FATS (20-35% of daily calories):
• Omega-3 rich foods: salmon, sardines, walnuts, flaxseeds
• Monounsaturated fats: olive oil, avocados, nuts
• Limit saturated fats and avoid trans fats
• Include variety of nuts and seeds

🌟 MICRONUTRIENT FOCUS:

VITAMINS:
• Vitamin D: Fatty fish, fortified foods, sunlight exposure
• B-Complex: Whole grains, leafy greens, lean meats
• Vitamin C: Citrus fruits, berries, bell peppers, broccoli
• Folate: Dark leafy greens, legumes, fortified grains

MINERALS:
• Iron: Lean red meat, spinach, lentils, pumpkin seeds
• Calcium: Dairy products, leafy greens, fortified plant milks
• Magnesium: Nuts, seeds, whole grains, dark chocolate
• Zinc: Oysters, beef, pumpkin seeds, chickpeas

🍽️ DAILY MEAL PLANNING:

BREAKFAST:
• Include protein, healthy fats, and complex carbs
• Examples: Oatmeal with berries and nuts, Greek yogurt with fruit

LUNCH:
• Balanced plate: 1/2 vegetables, 1/4 lean protein, 1/4 whole grains
• Include colorful vegetables for diverse nutrients

DINNER:
• Similar balance to lunch with emphasis on vegetables
• Consider lighter portions if eating late

SNACKS:
• Combine protein with fiber: apple with almond butter
• Avoid processed snacks and sugary drinks

💧 HYDRATION STRATEGY:
• 8-10 glasses of water daily
• Herbal teas and infused water for variety
• Limit caffeine and alcohol
• Monitor urine color for hydration status

🚫 FOODS TO LIMIT OR AVOID:
• Processed and packaged foods high in sodium
• Added sugars and artificial sweeteners
• Excessive saturated and trans fats
• Refined grains and white flour products
• High-sodium canned and frozen foods

📅 IMPLEMENTATION TIMELINE:
Week 1-2: Focus on increasing vegetable intake
Week 3-4: Optimize protein sources and timing
Week 5-6: Fine-tune healthy fat intake
Week 7-8: Establish sustainable meal patterns

Always consult with a registered dietitian for personalized nutrition counseling.
"""

    def _detailed_exercise_analysis(self):
        return """
🏃‍♂️ PERSONALIZED EXERCISE PROGRAM & FITNESS PLAN

💪 FITNESS ASSESSMENT:
Based on your blood test results and health markers, here's a comprehensive exercise program designed to optimize your health and fitness.

🎯 EXERCISE PRESCRIPTION:

CARDIOVASCULAR TRAINING:
• Frequency: 5 days per week
• Duration: 30-45 minutes per session
• Intensity: Moderate (60-70% max heart rate)
• Activities: Brisk walking, swimming, cycling, dancing, elliptical

STRENGTH TRAINING:
• Frequency: 2-3 days per week (non-consecutive days)
• Duration: 45-60 minutes per session
• Focus: All major muscle groups
• Sets/Reps: 2-3 sets of 8-12 repetitions
• Progression: Increase weight/resistance gradually

FLEXIBILITY & MOBILITY:
• Daily stretching routine (10-15 minutes)
• Yoga or Pilates 2-3 times per week
• Focus on major muscle groups and joints
• Include dynamic warm-up and static cool-down

BALANCE & COORDINATION:
• Tai Chi or balance exercises 2 times per week
• Single-leg stands, heel-to-toe walking
• Stability ball exercises
• Important for injury prevention

📅 WEEKLY EXERCISE SCHEDULE:

MONDAY: 30-min cardio + 15-min stretching
TUESDAY: Full-body strength training + flexibility
WEDNESDAY: 45-min moderate cardio activity
THURSDAY: Upper body strength + core work + stretching
FRIDAY: 30-min cardio of choice + balance exercises
SATURDAY: Lower body strength + yoga or Pilates
SUNDAY: Active recovery (gentle walk, stretching, or rest)

📈 PROGRESSION PLAN:

WEEKS 1-2: Establish routine, focus on proper form
• Start with lighter weights and shorter durations
• Emphasize consistency over intensity
• Learn proper exercise techniques

WEEKS 3-4: Increase duration and frequency
• Add 5-10 minutes to cardio sessions
• Increase strength training frequency if comfortable
• Monitor body response and recovery

WEEKS 5-8: Enhance intensity and add variety
• Increase resistance in strength training
• Add interval training to cardio routine
• Introduce new activities to prevent boredom

WEEKS 9-12: Optimize and reassess
• Fine-tune program based on progress
• Set new fitness goals
• Consider advanced exercise variations

⚠️ SAFETY GUIDELINES:

PRE-EXERCISE:
• Always warm up for 5-10 minutes
• Check with healthcare provider before starting
• Stay hydrated before, during, and after exercise
• Wear appropriate footwear and clothing

DURING EXERCISE:
• Monitor heart rate and exertion level
• Stop if experiencing chest pain, dizziness, or shortness of breath
• Use proper form to prevent injury
• Listen to your body and rest when needed

POST-EXERCISE:
• Cool down with 5-10 minutes of light activity
• Stretch major muscle groups
• Hydrate and refuel with balanced nutrition
• Allow adequate recovery time between sessions

📊 MONITORING & TRACKING:

WEEKLY METRICS:
• Total exercise minutes
• Resting heart rate trends
• Energy levels and sleep quality
• Body weight and measurements (monthly)

HEALTH INDICATORS:
• Blood pressure (if applicable)
• Blood sugar levels (if diabetic)
• Overall mood and stress levels
• Physical strength and endurance improvements

🎯 LONG-TERM GOALS:
• Achieve and maintain healthy body composition
• Improve cardiovascular fitness and endurance
• Build functional strength for daily activities
• Enhance flexibility and mobility
• Reduce risk of chronic diseases

Remember: Consistency is more important than perfection. Start slowly and build gradually for sustainable, long-term success.

Always consult with your healthcare provider and consider working with a certified fitness professional for personalized guidance.
"""

    def _document_verification(self):
        return """
✅ DOCUMENT VERIFICATION & ANALYSIS REPORT

📋 VERIFICATION STATUS: APPROVED

🔍 DOCUMENT ANALYSIS:
Your uploaded document has been successfully processed and verified as a legitimate medical blood test report.

VERIFICATION CHECKLIST:
✅ Document Format: Standard laboratory report format confirmed
✅ Medical Terminology: Appropriate clinical language detected
✅ Data Structure: Proper organization of test results
✅ Reference Ranges: Normal value ranges included
✅ Laboratory Information: Valid medical facility identifiers
✅ Test Parameters: Standard blood markers present
✅ Units of Measurement: Correct medical units used
✅ Date and Patient Info: Properly formatted identifiers

📊 CONTENT ASSESSMENT:

IDENTIFIED TEST CATEGORIES:
• Complete Blood Count (CBC) parameters
• Basic Metabolic Panel components
• Lipid profile measurements
• Liver function indicators
• Kidney function markers
• Additional specialized tests as applicable

DOCUMENT QUALITY METRICS:
• Readability Score: Excellent - Clear and legible text
• Completeness Rating: Comprehensive - All essential elements present
• Authenticity Assessment: Valid - Consistent with standard medical reports
• Processing Status: Ready for detailed medical analysis

🎯 ANALYSIS READINESS:
Your blood test report meets all criteria for comprehensive medical analysis. The document contains sufficient information for:

• Detailed health status assessment
• Personalized nutrition recommendations
• Customized exercise planning
• Risk factor evaluation
• Trend analysis (if previous results available)

✅ APPROVED FOR PROCESSING
Document successfully verified and ready for comprehensive medical analysis by our specialized AI agents.

📝 NEXT STEPS:
1. Comprehensive medical interpretation
2. Personalized health recommendations
3. Nutrition and lifestyle guidance
4. Exercise program development
5. Follow-up care suggestions

Note: This verification confirms document structure and format. For official medical validation, always consult with qualified healthcare professionals.
"""

# Initialize LLM
llm = FixedMockLLM()

# Create agents with fixed tools
doctor = Agent(
    role="Senior Medical Doctor and Blood Test Analyst",
    goal="Analyze blood test reports accurately and provide professional medical insights for query: {query}",
    verbose=True,
    memory=True,
    backstory="Experienced medical doctor with 15+ years in laboratory medicine and clinical diagnosis, specializing in comprehensive blood test interpretation.",
    tools=[BloodTestReportTool()],
    llm=llm,
    max_iter=2,
    allow_delegation=True
)

verifier = Agent(
    role="Medical Document Verifier",
    goal="Verify that uploaded documents are legitimate blood test reports and validate their content",
    verbose=True,
    memory=True,
    backstory="Medical records specialist with expertise in document validation and medical report authentication.",
    tools=[BloodTestReportTool()],
    llm=llm,
    max_iter=1,
    allow_delegation=False
)

nutritionist = Agent(
    role="Clinical Nutritionist and Dietitian",
    goal="Provide evidence-based nutrition recommendations based on blood test results and health markers",
    verbose=True,
    memory=True,
    backstory="Registered dietitian and clinical nutritionist specializing in medical nutrition therapy and personalized dietary planning.",
    tools=[BloodTestReportTool(), NutritionTool()],
    llm=llm,
    max_iter=2,
    allow_delegation=False
)

exercise_specialist = Agent(
    role="Clinical Exercise Physiologist",
    goal="Design safe and effective exercise programs based on blood test results and health status",
    verbose=True,
    memory=True,
    backstory="Certified clinical exercise physiologist with expertise in medical exercise prescription and fitness program development.",
    tools=[BloodTestReportTool(), ExerciseTool()],
    llm=llm,
    max_iter=2,
    allow_delegation=False
)
